from datetime import timedelta

from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from .models import Post


class PostModelTests(TestCase):
    def test_slug_is_autogenerated_from_title(self):
        post = Post.objects.create(title="Hello World", body="Body")
        self.assertEqual(post.slug, "hello-world")

    def test_get_absolute_url(self):
        post = Post.objects.create(title="My Post", body="Body")
        self.assertEqual(post.get_absolute_url(), reverse("posts:detail", kwargs={"slug": "my-post"}))

    def test_published_queryset_excludes_drafts_and_future(self):
        published = Post.objects.create(
            title="Published",
            body="Body",
            status=Post.Status.PUBLISHED,
        )
        draft = Post.objects.create(title="Draft", body="Body", status=Post.Status.DRAFT)
        future = Post.objects.create(
            title="Future",
            body="Body",
            status=Post.Status.PUBLISHED,
            published_at=timezone.now() + timedelta(days=1),
        )
        published_posts = Post.objects.published()
        self.assertIn(published, published_posts)
        self.assertNotIn(draft, published_posts)
        self.assertNotIn(future, published_posts)


class PostViewTests(TestCase):
    def setUp(self):
        self.post = Post.objects.create(
            title="Visible Post",
            summary="A teaser",
            body="Full body text",
            status=Post.Status.PUBLISHED,
        )
        self.draft = Post.objects.create(
            title="Hidden Draft",
            body="Secret",
            status=Post.Status.DRAFT,
        )

    def test_list_shows_published_only(self):
        response = self.client.get(reverse("posts:list"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Visible Post")
        self.assertNotContains(response, "Hidden Draft")

    def test_detail_renders_published_post(self):
        response = self.client.get(self.post.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Full body text")

    def test_detail_404_for_draft(self):
        response = self.client.get(reverse("posts:detail", kwargs={"slug": self.draft.slug}))
        self.assertEqual(response.status_code, 404)
